### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

### ISSUE THREAD

**Issue by Soundtoxin** [ranger/ranger#2069]
#### Runtime Environment

- Operating system and version: Void
- Terminal emulator and version: Alacritty 0.41 on another machine connecting over ssh
- Python version: 3.8.4
- Ranger version/commit: 1.9.3
- Locale: en_us.UTF-8

#### Current Behavior
crashes on launch

#### Expected Behavior
normal launch and function as experienced on other  distros

#### Steps to reproduce
1. launch ranger on void

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.8.4 (default, Jul 17 2020, 11:12:18) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.8/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

edit: ran on the local machine it doesn't crash, my $TERM is screen-256color over ssh, and I'm inside tmux on the machine I'm sshing from.

**Comment by toonn** [comment]
I think this was fixed on master. Could you check?

**Comment by ImFyatto** [comment]
We are same problem,you can try edit /etc/sudoers and add:
```
Defaults    !env_reset
```
(keep currently environment variable)

**Comment by toonn** [comment]
@Soundtoxin's problem isn't related to sudo or a misconfigured environment.

**Comment by Soundtoxin** [comment]
> I think this was fixed on master. Could you check?

I don't have much experience building stuff myself, but from what I can tell it's still crashing. I'm not 100% sure I'm using the ranger that I built. I tried running it from `/usr/local/bin/ranger` instead of the default location after the `sudo make install`.

```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Aug 11 2020, 13:06:53) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.8/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

It's calling itself the same version which seems wrong to me. Should it still be 1.9.3 even if I built it?

**Comment by toonn** [comment]
@Soundtoxin, you can simply run `python3 ranger.py` from the repo.

**Comment by Soundtoxin** [comment]
Oh, nice! That *does* work, so it is fixed on master then. No more crash using the same environment.
