### ISSUE TITLE
Using "f" in root crashes ranger

### ISSUE THREAD

**Issue by TheSimpleZ** [ranger/ranger#2387]
#### Runtime Environment

- Operating system and version: Linux 5.10.42-1-MANJARO
- Terminal emulator and version: alacritty 0.8.0
- Python version:  3.9.5 (default, May 24 2021, 12:50:35) [GCC 11.1.0]
- Ranger version/commit: ranger-master
- Locale: en_DK.UTF-8

#### Current Behavior
Open the terminal and navigate to /.
Use "f" and try to search for "etc"
As I type the "t" in "etc" ranger crashes.

#### Expected Behavior
It should find the existing "etc" folder.

#### Context
I'm just trying to use the basic search functionality of ranger.

#### Steps to reproduce
1. Open terminal
2. `cd /`
3. `ranger`
4. `f`
5. `et`

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger/config/commands.py", line 1520, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.9/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.9/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by hektr** [comment]
can't reproduce your error. Clone master repository and run ranger from it: 

 `git clone https://github.com/ranger/ranger.git`
`cd ranger`
`./ranger.py`

**Comment by toonn** [comment]
I suspect this was fixed on master, yes. Could you verify @TheSimpleZ?

**Comment by TheSimpleZ** [comment]
Right! 
I tried cloning ranger and running it, and it seems to work fine. 
What confused me was the fact that `ranger --version` displayed "ranger-master" as the version, which lead me to believe I had the latest changes. 

Originally I had the `ranger` package installed from AUR. It seems like that might be an older version. 
Changing to `ranger-git` fixed the issue. `ranger --version` still shows the same message, but the "f" command is now working fine 👍🏼

**Comment by hektr** [comment]
> Right!
> I tried cloning ranger and running it, and it seems to work fine.
> What confused me was the fact that `ranger --version` displayed "ranger-master" as the version, which lead me to believe I had the latest changes.
> 
> Originally I had the `ranger` package installed from AUR. It seems like that might be an older version.
> Changing to `ranger-git` fixed the issue. `ranger --version` still shows the same message, but the "f" command is now working fine 👍🏼
> 
> Thanks for pointing me in the right direction!

Why from aur? 
`pacman -S ranger` should work

**Comment by TheSimpleZ** [comment]
Sorry, I wrote that too quickly. The original I had installed was through **pacman**. That was the one causing the error. 
I then installed `ranger-git` from AUR. And that worked :)
