### ISSUE TITLE
Pager fork failure on Debian

### ISSUE THREAD

**Issue by ubershmekel** [ranger/ranger#750]
OS and ranger version:

    yuv@debian:~$ uname -a
    Linux debian 4.8.6-x86_64-linode78 #1 SMP Tue Nov 1 14:51:21 EDT 2016 x86_64 GNU/Linux

    yuv@debian:~$ ranger --version
    ranger-stable 1.6.1
    Python 2.7.9 (default, Jun 29 2016, 13:08:31)
    [GCC 4.9.2]

How to reproduce:

    sudo apt-get install ranger
    ranger
    # hit the `?` key

Result:

    /usr/bin/sensible-pager: 3: /usr/bin/sensible-pager: Cannot fork

Expected result:

    The ranger MAN page.

Workaround:

    yuv@debian:~$ PAGER=less

This seems to be similar to http://git.net/ml/general/2015-05/msg12264.html "Subject: Bug#784875: ranger: rifle cannot open file in pager if PAGER is not set"

**Comment by ubershmekel** [comment]
This issue was resolved in newer versions of ranger. So the fix is:

    git clone https://github.com/ranger/ranger
    cd ranger
    sudo make install

Which brought me from ranger 1.6.1 to 1.8.0. I hope the debian repository can be updated.

**Comment by sim590** [comment]
When I manually updated to 1.8.0, the bug was gone. However, now my package manager automatically updated to 1.8.1 from unstable release and the bug is back again...

**Comment by nfnty** [comment]
Have you tested `master`?

**Comment by sim590** [comment]
Indeed, I haven't. But, now yes and I get this:
```
ranger version: 1.8.1
Python version: 2.7.13
Locale: en_CA.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 108, in main
    load_settings(fm, args.clean)
  File "/usr/local/lib/python2.7/dist-packages/ranger/core/main.py", line 323, in load_settings
    import commands as commands_custom
  File "/home/simon/.config/ranger/commands.py", line 348, in <module>
    class setlocal(set_):
  File "/home/simon/.config/ranger/commands.py", line 353, in setlocal
    PATH_RE = re.compile(r'^\s*path="?(.*?)"?\s*$')
NameError: name 're' is not defined

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```
which is unrelated to this issue, but I want to point out that your master branch is broken.

**Comment by sim590** [comment]
I have tried two or three parent commits of master and I still get the error. I'm not really up to doing some `git bisect` right now.

**Comment by nfnty** [comment]
You need to update your `commands.py`.

**Comment by nfnty** [comment]
As the error says, add `import re`.

**Comment by sim590** [comment]
Alright. I can confirm that `master` is fine.

I also tested the 1.8.1 release and it's fine... Seems like the issue is with the debian package. They seem to apply this patch:
```diff
From: Vern Sun <s5unty@gmail.com>
Date: Thu, 6 Mar 2014 14:13:36 +0800
Subject: make sensible decisions on which pager and editor
Forwarded: yes

--- a/ranger/__init__.py
+++ b/ranger/__init__.py
@@ -24,7 +24,7 @@ TICKS_BEFORE_COLLECTING_GARBAGE = 100
 TIME_BEFORE_FILE_BECOMES_GARBAGE = 1200
 MAX_RESTORABLE_TABS = 3
 MACRO_DELIMITER = '%'
-DEFAULT_PAGER = 'less'
+DEFAULT_PAGER = 'sensible-pager'
 CACHEDIR = os.path.expanduser("~/.cache/ranger")
 USAGE = '%prog [options] [path]'
 VERSION = 'ranger-stable %s\n\nPython %s' % (__version__, sys.version)
--- a/ranger/ext/rifle.py
+++ b/ranger/ext/rifle.py
@@ -22,8 +22,8 @@ import sys
 __version__ = 'rifle 1.8.1'
 
 # Options and constants that a user might want to change:
-DEFAULT_PAGER = 'less'
-DEFAULT_EDITOR = 'vim'
+DEFAULT_PAGER = 'sensible-pager'
+DEFAULT_EDITOR = 'sensible-editor'
 ASK_COMMAND = 'ask'
 ENCODING = 'utf-8'
 ```
which enables the bug.

**Comment by nfnty** [comment]
Then you need to report this to your distro.

**Comment by sim590** [comment]
As a contributor to this project, do you think this patch is bad? Why doesn't this work? Can you support this config or you simply don't want to?

**Comment by nfnty** [comment]
Do you have this problem when running with `ranger --clean` on `1.8.1`?

Could you test applying that patch on `master` and running with `ranger --clean`?

**Comment by Vifon** [comment]
@sim590 It's conforming to the Debian (and only Debian) standards but at the same time all the bugs and quirks of `sensible-pager` are affecting ranger/rifle too. Which is the case here.

**Comment by mati75** [comment]
I'm the last packager of ranger in Debian. I will drop this from patch, but sensible-editor must stay.

**Comment by sim590** [comment]
Ok. Now, I don't understand really what changed and I cannot reproduce the bug even with the same packages I did produce the bug initially. I'm a bit confused right now and I believe the reason of the bug is not clear.
