### ISSUE TITLE
Wrap lines in preview column

### ISSUE THREAD

**Issue by nonamethanks** [ranger/ranger#792]
#### ISSUE TYPE
- Improvement/feature request

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux
- Terminal emulator and version: urxvt
- Python version: 3.6.0
- Ranger version/commit: cloned moments ago

#### EXPECTED BEHAVIOR
A text file consisting of one or more lines longer than the preview allows to show would ideally wrap lines

#### CURRENT BEHAVIOR
Text file previews do not currently wrap.

#### CONTEXT
I was trying to figure out how to edit scope.sh in order to make text previews wrap, however I couldn't manage to do it. I have found [a pretty old post ](https://lists.nongnu.org/archive/html/ranger-users/2012-10/msg00014.html) and [another issue](https://github.com/ranger/ranger/issues/309) but those are of no help because the lines in question have changed since then and my thrown-together attempts did not bear fruit. 

#### POSSIBLE SOLUTIONS
Any help would be greatly appreciated. I'm sure it would also be great for anyone who happens to search for this in the future - a direct change to the default-shipped scope.sh is not necessary of course.

**Comment by nfnty** [comment]
First use the new `scope.sh` from `master`.

You need to pipe the command you want to have wrapped lines into something that inserts a newline after every `$PV_WIDTH` characters.

Read this for more info on how to do that easily: https://stackoverflow.com/questions/1187078/how-to-insert-a-new-line-character-after-a-fixed-number-of-characters-in-a-file

**Comment by jottr** [comment]
I am running into the same issue. 
It is unclear to me where I would need to set the `$PV_WIDTH` in this [specific case](https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh#L219).  
I am sure some further pointers or a working example would be quite helpful.

**Comment by toonn** [comment]
Hmm, does this happen when you disable `preview_files`?

**Comment by jottr** [comment]
I'm not sure I understand the question. 
I have `set preview_files true` in my `rc.conf`. Setting it to `false` simply disables file previews completely.

**Comment by jottr** [comment]
Yes, it still happens when I set `use_preview_script` to `false`.

**Comment by toonn** [comment]
That's what I thought. So this can only be solved in ranger's code, not in `scope.sh`. I'm not sure what to do with it since an option just for plaintext preview wrapping is a little silly. I think you could add wrapping at line 1035 of `ranger/core/actions.py`.

**Comment by jottr** [comment]
Ok, so this is a general problem with the implementation of rangers preview feature then? 
I'm surprised that this is not considered more serious, since it basically makes text preview in ranger kind of useless. 
It is possible to have syntax highlighting, but text is not properly wrapped? That can't be right.  
Can this be kindly reopened then and elevated to `bug` level? 

I'm actually surprised now that the issue was closed so quickly by @nfnty in the first place if this is a an implementation scope problem and can't be fixed in a users configuration.

**Comment by toonn** [comment]
Well, @nfnty, was under the impression this concerned `scope.sh` previews which you can easily wrap yourself and afaik are already wrapped in the default `scope.sh` at least for pdfs.

You can consider this a serious bug but I don't, I use the previews just as that, *previews*. The preview column is not a substitute for a pager or a document reader. By truncating each line you can still get the gist of a document because you see more lines. For pdfs we already do the wrapping because that eliminates all the silly whitespace and linebreaking issues converting pdf layout to plaintext brings.

It shouldn't be too hard to patch for yourself if you so desperately want this. If we do anything about it though it'd probably be optionally running plaintext previews through `scope.sh` as well, rather than the current way where ranger has plaintext previews built in. It's built in because plaintext's easy to read anyway and this way you don't have to rely on a script you may not trust.

**Comment by jottr** [comment]
Thx for reopening this. 
I don't consider this a serious bug, but I do consider it a bug. 
IMHO software, especially software targeting power users as their main user base, should try and reduce cognitive friction and not behave unexpectedly. 
Since ranger wraps lines in some cases, but not all, no matter why this is the case, using the preview feature generates said friction. 
I understand that ranger not consistently wrapping lines works for you, probably also, because you are used to this exact quirk - a normal end user has no means of telling what behaviour to expect. 
  
Let's take a specific, probably common use case: 

Currently, I'm get acquainted with a new large code base. The repository contains different kinds of files, which I need to quickly inspect. It contains documentation in the form of markdown files, which I'd like to quickly skim, but can't, since the text is not being wrapped.
This leads me to having switch context, i.e. open vim, read the file, and close it again. 
Instead I'd love to be able to quickly read a modules documentation, decide if I need it, and move it to another project, if I deem it relevant. 
To me, this is significantly more important, than having image previews in my terminal. 

> It shouldn't be too hard to patch for yourself if you so desperately want this.
Sure I could. But why not take mine and @nonamethanks input as a suggestion that this is a feature that might be required by the user base?

**Comment by gennad** [comment]
+1 for this feature

**Comment by ploum** [comment]
Trying to get a nice preview for thousands of markdown files I'm working with. If I read this issue correctly, the correct way to solve this would be to run txt files through scope.sh?  I've tried to add a .md extension in scope.sh but it seems to have no effect (I may be missing something).

As a python developer myself, I have no problem working on the issue if the dev team is clear about what they want and what would be needed for such a feature to be accepted.

**Comment by ploum** [comment]
well, I managed to do it. The solution for me is to add, in scope.sh, the following :

 # Markdown
          markdown|md|txt)
           pygmentize -f 'terminal256' -O "style=${PYGMENTIZE_STYLE}"   -- "${FILE_PATH}"| fmt -s -w "78" && exit 5
    ;;

**Comment by toonn** [comment]
I have an open PR implementing this: #1322

**Comment by mik13ST** [comment]
I think this can be closed, the PR is merged. There is `Fixes ...` in the commit message, but it references a different issue (which is a duplicate of this one).

**Comment by AtaarSatag** [comment]
> First use the new `scope.sh` from `master`.
> 
> You need to pipe the command you want to have wrapped lines into something that inserts a newline after every `$PV_WIDTH` characters.
> 
> Read this for more info on how to do that easily: https://stackoverflow.com/questions/1187078/how-to-insert-a-new-line-character-after-a-fixed-number-of-characters-in-a-file

Here is what was worked for me:  `<stdout_of_command> | sed -e "s/.\{$PV_WIDTH\}/&\n↪/g" && exit 5`, i.e. after a new line, we can add a designation for line wrapping?

Normal
<img width="1903" height="245" alt="Image" src="https://github.com/user-attachments/assets/e1da50ea-4c1c-43ef-a0a2-cbce0d355e2b" />

Preview
<img width="1681" height="466" alt="Image" src="https://github.com/user-attachments/assets/1899fa91-5914-476a-affd-0c95226d1b61" />
